# Generated by Django 4.2 on 2023-04-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateTuple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.CharField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'DateTuple',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('department_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Examselection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exam_selection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Examtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=25)),
                ('module_code', models.CharField(max_length=10)),
                ('module_name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'examTable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('module_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('module_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'modules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NormalEnrollments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'normalenrollments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('program_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Programs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RepeatEnrollments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'studentrepeats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_number', models.IntegerField(primary_key=True, serialize=False)),
                ('year_id', models.IntegerField()),
            ],
            options={
                'db_table': 'semester',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YearOfStudy',
            fields=[
                ('year_id', models.IntegerField(primary_key=True, serialize=False)),
                ('year_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'year_of_study',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamtableHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=25)),
                ('module_code', models.CharField(max_length=10)),
                ('module_name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'examtable_history',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uName', models.CharField(max_length=30)),
                ('uemail', models.CharField(max_length=30)),
                ('upasswd', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
