# Generated by Django 4.2 on 2023-04-05 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datetuple',
            options={},
        ),
        migrations.AlterModelOptions(
            name='departments',
            options={},
        ),
        migrations.AlterModelOptions(
            name='examselection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='examtable',
            options={},
        ),
        migrations.AlterModelOptions(
            name='modules',
            options={},
        ),
        migrations.AlterModelOptions(
            name='normalenrollments',
            options={},
        ),
        migrations.AlterModelOptions(
            name='programs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='repeatenrollments',
            options={},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={},
        ),
        migrations.AlterModelOptions(
            name='yearofstudy',
            options={},
        ),
    ]
