# Generated by Django 4.2 on 2023-04-05 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0002_alter_datetuple_options_alter_departments_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateTuple',
        ),
        migrations.DeleteModel(
            name='Examselection',
        ),
        migrations.DeleteModel(
            name='Examtable',
        ),
        migrations.DeleteModel(
            name='NormalEnrollments',
        ),
        migrations.DeleteModel(
            name='Programs',
        ),
        migrations.DeleteModel(
            name='RepeatEnrollments',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
