# Generated by Django 4.2 on 2023-05-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0004_datetuple_examselection_examtable_programs_students_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('num_of_students', models.IntegerField()),
                ('timing', models.CharField(max_length=50)),
                ('module_code', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField()),
                ('classroom_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Classroom_Allocation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'classrooms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExaminationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'examination_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=6)),
                ('year', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exam_semester',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invigilators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'invigilators',
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='normalenrollments',
            old_name='id',
            new_name='enrollment_id',
        ),
        migrations.RenameField(
            model_name='repeatenrollments',
            old_name='id',
            new_name='enrollment_id',
        ),
        migrations.AddField(
            model_name='normalenrollments',
            name='num_students',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
